"""
SatQuery AI - Backend API Test Suite
Verifies health, routing, agentic classification, and sample endpoints.

NOTE: The pipeline executes the real domain-adapted inference stack:
RemoteCLIP-ViT-B/32 foundation backbone + trained BigEarthNet domain adapter
(see backend/app/models/remote_clip.py). test_query_single_optical asserts the
model actually ran (features returned, confidence >= 0.70, models_executed
populated, audit hash computed). VQA text answers are generated by the local
neural pipeline with honest telemetry; these tests assert on execution and
routing correctness rather than on invented prose.
"""

from fastapi.testclient import TestClient
import json
import pytest
from backend.app.main import app

client = TestClient(app)


def test_root():
    response = client.get("/")
    assert response.status_code == 200
    data = response.json()
    assert data["app"] == "SatQuery AI"
    assert data["status"] == "operational"


def test_health():
    response = client.get("/api/health")
    assert response.status_code == 200
    data = response.json()
    assert data["status"] in ("healthy", "degraded")
    assert data["live_stac_streaming"] in ("online", "standby")
    assert "integrations" in data
    assert data["sample_data_ready"] is True


def test_samples_manifest():
    response = client.get("/api/samples/manifest")
    assert response.status_code == 200
    data = response.json()
    assert "optical_samples" in data
    assert "inventory" in data
    assert data["inventory"]["optical_count"] >= 2


def test_samples_vqa():
    response = client.get("/api/samples/vqa")
    assert response.status_code == 200
    data = response.json()
    assert "vrsbench_samples" in data or "cdvqa_samples" in data


@pytest.mark.slow
def test_query_single_optical():
    payload = {
        "query": "Identify institutional buildings in the satellite image",
        "bbox": [72.50, 23.00, 72.60, 23.08],
        "modality": "single_image",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "optical_vqa"
    assert data["geojson"]["type"] == "FeatureCollection"
    # Real RemoteCLIP model execution assertions:
    assert len(data["geojson"]["features"]) > 0
    # Confidence must be a real softmax posterior in [0,1] — never a fabricated floor.
    assert 0.0 <= data["confidence"] <= 1.0
    assert data["ai_engine_active"] in ("remoteclip_vlm", "ollama_qwen2.5_3b")
    # Per-feature confidence must be the image-level posterior (labelled), or null.
    prop = data["geojson"]["features"][0]["properties"]
    assert prop.get("confidence_basis") in ("image_class_posterior", "unavailable")
    if prop.get("confidence") is not None:
        assert prop["confidence_basis"] == "image_class_posterior"
    assert data["telemetry"]["pipeline_status"] == "operational"
    assert len(data["telemetry"]["models_executed"]) > 0
    assert "audit_hash" in data
    assert data["audit_hash"].startswith("SHA256-")
    assert data["telemetry"]["audit_hash"] == data["audit_hash"]


@pytest.mark.slow
def test_query_bitemporal_change():
    payload = {
        "query": "What changed between T1 and T2 in the building area?",
        "bbox": [72.50, 23.00, 72.60, 23.08],
        "modality": "bitemporal",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "bitemporal_change"
    assert data["geojson"]["type"] == "FeatureCollection"
    assert len(data["geojson"]["features"]) > 0
    assert data["telemetry"]["pipeline_status"] == "operational"
    assert data["findings"]["surfaceAreaModifiedKm2"] is not None
    assert data["findings"]["surfaceAreaModifiedKm2"] > 0
    # Honest DSP posterior range, not a fabricated floor/ceiling.
    assert 0.0 <= data["confidence"] <= 1.0
    assert data["ai_engine_active"] in ("bitemporal_change_dsp", "ollama_qwen2.5_3b")
    # Anti-fabrication: the bitemporal path is radiometric DSP, never InSAR/DInSAR.
    blob = (data["answer"] + str(data["dagNodes"]) + str(data["telemetry"])).lower()
    for forbidden in ("dinsar", "insar", "sbas"):
        assert forbidden not in blob


@pytest.mark.slow
def test_query_crossmodal_fusion():
    payload = {
        "query": "Use SAR radar to pierce the heavy cloud cover and identify structures",
        "bbox": [72.50, 23.00, 72.60, 23.08],
        "modality": "cross_modal",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "crossmodal_fusion"
    assert data["geojson"]["type"] == "FeatureCollection"
    assert len(data["geojson"]["features"]) > 0
    assert data["findings"]["piercedCloudPercent"] is not None
    assert 0.0 <= data["findings"]["piercedCloudPercent"] <= 100.0


@pytest.mark.slow
def test_query_no_gemini_field_accepted():
    """Regression guard: the API must not require or depend on a gemini_api_key field."""
    payload = {
        "query": "Analyze this scene",
        "bbox": [72.50, 23.00, 72.60, 23.08],
        "gemini_api_key": "should-be-ignored-or-rejected",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["telemetry"]["pipeline_status"] == "operational"


@pytest.mark.slow
def test_query_visual_grounding():
    """Verify that a region grounding query routes to visual_grounding intent and returns bounded polygons."""
    payload = {
        "query": "Highlight all water bodies and outline the riverbank in this scene",
        "bbox": [72.50, 23.00, 72.60, 23.08],
        "modality": "single_image",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "visual_grounding"
    assert data["geojson"]["type"] == "FeatureCollection"
    assert len(data["geojson"]["features"]) > 0


@pytest.mark.slow
def test_query_scene_captioning():
    """Verify that scene description queries route to scene_captioning intent."""
    payload = {
        "query": "Describe the land-cover breakdown and major objects visible in this image",
        "bbox": [72.50, 23.00, 72.60, 23.08],
        "modality": "single_image",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "scene_captioning"
    assert len(data["answer"]) > 20


@pytest.mark.slow
def test_ai_key_endpoint_removed():
    """Ensure dead /api/settings/ai-key endpoint is completely removed (returns 404)."""
    response = client.post("/api/settings/ai-key", json={"api_key": "test", "provider": "gemini"})
    assert response.status_code == 404 or response.status_code == 405


@pytest.mark.slow
def test_reproducible_audit_hash():
    """Verify that re-running identical queries produces the identical cryptographic audit hash."""
    payload = {
        "query": "Identify institutional buildings in the satellite image",
        "bbox": [72.50, 23.00, 72.60, 23.08],
        "modality": "single_image",
    }
    res1 = client.post("/api/query", json=payload)
    assert res1.status_code == 200
    data1 = res1.json()

    res2 = client.post("/api/query", json=payload)
    assert res2.status_code == 200
    data2 = res2.json()

    assert data1["audit_hash"] == data2["audit_hash"], (
        f"Audit hashes must be identical! Got {data1['audit_hash']} vs {data2['audit_hash']}"
    )


@pytest.mark.slow
def test_benchmark_catalog():
    response = client.get("/api/benchmark/catalog")
    assert response.status_code == 200
    data = response.json()
    assert "challenges" in data
    assert data["count"] > 0


@pytest.mark.slow
def test_benchmark_evaluate_no_artificial_floor():
    """Regression guard: scores must not be artificially floored when there's no match."""
    payload = {
        "query": "Did the areas of non-vegetated ground surface change?",
        "ground_truth": "yes",
        "modality": "bitemporal",
    }
    response = client.post("/api/benchmark/evaluate", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["status"] == "success"
    assert "score_percent" in data
    assert "metrics" in data
    # With no model wired in, the honest score should NOT be artificially inflated.
    # (Previously this was floored at 75% regardless of actual match quality.)
    assert data["score_percent"] < 75.0 or data["metrics"]["exact_match"] is True


def test_upload_geojson():
    geojson_content = (
        b'{"type": "FeatureCollection", "features": [{"type": "Feature", "properties": {}, '
        b'"geometry": {"type": "Polygon", "coordinates": [[[72.5, 23.0], [72.6, 23.0], [72.6, 23.1], [72.5, 23.1], [72.5, 23.0]]]}}]}'
    )
    files = {"file": ("test.geojson", geojson_content, "application/geo+json")}
    response = client.post("/api/upload", files=files)
    assert response.status_code == 200
    data = response.json()
    assert data["file_type"] == "geojson"
    assert data["features_count"] == 1
    assert data["bbox"] == [72.5, 23.0, 72.6, 23.1]


@pytest.mark.slow
def test_sector_aware_spatial_grounding_galwan():
    """Verify that querying Galwan produces genuine Galwan coordinates, not Ahmedabad."""
    payload = {
        "query": "Map high-altitude mountain causeway and forward outpost structures",
        "sector_id": "galwan-sar",
        "bbox": [78.22, 34.74, 78.28, 34.79],
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["telemetry"]["sector_id"] == "galwan-sar"
    assert data["findings"]["sectorName"] == "Galwan Valley Tactical Outpost"
    assert "Galwan Valley" in data["answer"]

    # Verify coordinates are in Ladakh (lon ~78, lat ~34), NOT Ahmedabad (lon ~72, lat ~23)
    features = data["geojson"]["features"]
    assert len(features) > 0
    first_coord = features[0]["geometry"]["coordinates"][0][0]
    assert 78.0 <= first_coord[0] <= 78.5, f"Expected lon in Galwan, got {first_coord[0]}"
    assert 34.5 <= first_coord[1] <= 35.0, f"Expected lat in Galwan, got {first_coord[1]}"
    # Coordinate type sanity: must be Python float
    assert isinstance(first_coord[0], float)
    assert isinstance(first_coord[1], float)


@pytest.mark.slow
def test_sector_aware_sriharikota_change():
    """Verify bi-temporal change detection at Sriharikota uses correct dates and spaceport bounds."""
    payload = {
        "query": "Detect launchpad complex groundwork and assembly changes between T1 and T2",
        "sector_id": "sdsc-sriharikota",
        "modality": "bitemporal",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "bitemporal_change"
    assert data["findings"]["sectorName"] == "Satish Dhawan Space Centre (SDSC SHAR)"
    assert data["findings"]["temporalInterval"] == "2024-01-15 (T1) -> 2024-04-10 (T2)"

    features = data["geojson"]["features"]
    assert len(features) > 0
    first_coord = features[0]["geometry"]["coordinates"][0][0]
    assert 80.1 <= first_coord[0] <= 80.4, f"Expected lon in Sriharikota, got {first_coord[0]}"
    assert 13.6 <= first_coord[1] <= 13.9, f"Expected lat in Sriharikota, got {first_coord[1]}"


@pytest.mark.slow
def test_sector_aware_malacca_sar_cloud_piercing():
    """Verify SAR cloud piercing over Malacca Strait detects ships and reports radar metrics."""
    payload = {
        "query": "Pierce tropical cloud cover with Sentinel-1 SAR to map cargo vessel traffic",
        "sector_id": "malacca-chokepoint",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert data["intent"] == "crossmodal_fusion"
    assert data["findings"]["sectorName"] == "Malacca Strait Maritime Corridor"
    assert data["findings"]["piercedCloudPercent"] is not None
    assert 0.0 <= data["findings"]["piercedCloudPercent"] <= 100.0

    features = data["geojson"]["features"]
    assert len(features) > 0
    first_coord = features[0]["geometry"]["coordinates"][0][0]
    assert 101.3 <= first_coord[0] <= 101.7, f"Expected lon in Malacca Strait, got {first_coord[0]}"
    assert 2.3 <= first_coord[1] <= 2.7, f"Expected lat in Malacca Strait, got {first_coord[1]}"


@pytest.mark.slow
def test_bigearthnet_benchmark_evaluation():
    """Verify BigEarthNet benchmark challenges can be fetched and evaluated honestly."""
    cat_resp = client.get("/api/benchmark/catalog")
    assert cat_resp.status_code == 200
    challenges = cat_resp.json()["challenges"]
    ben_challenges = [c for c in challenges if c["id"].startswith("ben-") or "bigearthnet" in c.get("dataset", "").lower()]
    assert len(ben_challenges) > 0, "BigEarthNet challenges must be available in catalog"

    first_ben = ben_challenges[0]
    query_text = first_ben.get("question") or first_ben.get("query")
    eval_resp = client.post("/api/benchmark/evaluate", json={
        "query": query_text,
        "ground_truth": first_ben["ground_truth"],
        "modality": first_ben.get("suggested_modality", "single_image"),
    })
    assert eval_resp.status_code == 200
    eval_data = eval_resp.json()
    assert eval_data["status"] == "success"
    assert "score_percent" in eval_data
    assert "metrics" in eval_data


@pytest.mark.slow
def test_change_detection_physical_gsd_area():
    """Verify change detection computes physical GSD area and true GeoJSON polygon geometry."""
    payload = {
        "query": "Detect land cover changes between T1 and T2",
        "sector_id": "isro-sac",
        "modality": "bitemporal",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    features = data["geojson"]["features"]
    assert len(features) > 0
    f = features[0]
    # Verify geometry is valid GeoJSON Polygon with coordinates
    assert f["geometry"]["type"] in ("Polygon", "MultiPolygon")
    assert "area_km2" in f["properties"]
    assert f["properties"]["area_km2"] > 0
    assert "pixel_count" in f["properties"]
    assert f["properties"]["pixel_count"] > 0
    # Confidence is calibrated
    assert 0.0 < data["confidence"] <= 1.0


@pytest.mark.slow
def test_sar_fusion_signal_to_clutter_calibration():
    """Verify SAR cross-modal analysis computes Signal-to-Clutter Ratio and calibrated confidence."""
    payload = {
        "query": "Detect radar scatterers and pierce cloud cover with Sentinel-1 SAR",
        "sector_id": "galwan-sar",
        "modality": "crossmodal_fusion",
    }
    response = client.post("/api/query", json=payload)
    assert response.status_code == 200
    data = response.json()
    features = data["geojson"]["features"]
    assert len(features) > 0
    f = features[0]
    assert "signal_to_clutter_ratio_db" in f["properties"]
    assert "mean_backscatter_db" in f["properties"]
    assert "confidence" in f["properties"]
    # Real signal-to-clutter heuristic posterior, or null when no targets detected.
    if f["properties"]["confidence"] is not None:
        assert 0.0 <= f["properties"]["confidence"] <= 1.0
    # Overall confidence is dynamic and honest.
    assert isinstance(data["confidence"], float)
    assert data["ai_engine_active"] in ("crossmodal_sar_fusion_dsp", "ollama_qwen2.5_3b")


def test_sector_timeline_authentic_revisit():
    """Verify sector timeline delivers authentic satellite revisit passes without fabricated tactical events."""
    response = client.get("/api/samples/sector-timeline/isro-sac?time_range=7d")
    assert response.status_code == 200
    data = response.json()
    assert data["sectorId"] == "isro-sac"
    assert len(data["passes"]) > 0
    first_pass = data["passes"][0]
    assert first_pass["is_simulated"] is True
    assert "acquisition_type" in first_pass

    # Confirm sensationalized drama is eliminated across all passes
    for p in data["passes"]:
        desc = p["changeDescription"]
        assert "fuel lines" not in desc
        assert "drilling rig" not in desc
        assert "bulldozer" not in desc


def test_inspect_pixel_endpoint():
    """Verify that inspecting a pixel point returns coordinates, spectral indices, and land cover classification."""
    payload = {
        "lat": 23.025,
        "lon": 72.520,
        "bbox": [72.500, 23.015, 72.540, 23.035]
    }
    response = client.post("/api/inspect-pixel", json=payload)
    assert response.status_code == 200
    data = response.json()
    assert "coordinates" in data
    assert "indices" in data
    assert "ndvi" in data["indices"]
    assert "ndwi" in data["indices"]
    assert "ndbi" in data["indices"]
    assert "sar_backscatter_proxy_db" in data["indices"]
    assert "proxy" in data["indices"]["sar_db_note"].lower()
    assert "land_cover_class" in data


# ---------------------------------------------------------------------------
# Anti-fabrication regression guards (SIH26167 remediation)
# ---------------------------------------------------------------------------

def test_uploaded_garbage_tif_rejected():
    """E-1 guard: a 4-byte non-raster must be rejected, not accepted as a valid TIFF."""
    files = {"file": ("garbage.tif", b"\x00\x01\x02\x03", "image/tiff")}
    response = client.post("/api/upload", files=files)
    assert response.status_code == 400


@pytest.mark.slow
def test_distinct_inputs_yield_distinct_audit_hash():
    """Two genuinely different sectors must produce different evidence hashes."""
    base = {"modality": "bitemporal", "query": "Detect surface changes between the two acquisitions"}
    joshi = client.post("/api/query", json={**base, "sector_id": "joshimath-subsidence"}).json()
    malacca = client.post("/api/query", json={**base, "sector_id": "malacca-chokepoint"}).json()
    assert joshi["audit_hash"] != malacca["audit_hash"]


@pytest.mark.slow
def test_no_insar_claim_on_bitemporal():
    """No bitemporal response may claim InSAR/DInSAR/SBAS capability."""
    data = client.post("/api/query", json={
        "query": "Quantify subsidence between the two acquisitions",
        "sector_id": "joshimath-subsidence",
        "modality": "bitemporal",
    }).json()
    blob = json.dumps(data).lower()
    for forbidden in ("dinsar", "insar", "sbas"):
        assert forbidden not in blob


@pytest.mark.slow
def test_telemetry_provenance_block_present():
    """Telemetry must carry honest imagery provenance, not bare claims."""
    data = client.post("/api/query", json={
        "query": "Assess the terrain", "sector_id": "joshimath-subsidence",
    }).json()
    t = data["telemetry"]
    for key in ("is_real_image", "is_simulated", "imagery_origin",
                "raster_is_georeferenced", "data_provenance", "live_stream_status"):
        assert key in t, f"telemetry missing {key}"


@pytest.mark.slow
def test_live_stream_opt_in_and_honest_default():
    """C-1 guard: live stream is off by default; opt-in returns an honest status."""
    default = client.post("/api/query", json={
        "query": "Assess the terrain", "sector_id": "joshimath-subsidence",
    }).json()
    assert default["live_satellite_stream"] is None
    assert default["telemetry"]["live_stream_status"] == "not_requested"

    opt_in = client.post("/api/query", json={
        "query": "Assess the terrain", "sector_id": "joshimath-subsidence",
        "context_hints": {"live_stream": True},
    }).json()
    assert opt_in["telemetry"]["live_stream_status"] in ("online", "unavailable", "error")
    if opt_in["live_satellite_stream"] is not None:
        ls = opt_in["live_satellite_stream"]
        assert "pil_image" not in ls
        assert ls["status"] == "online"
        assert ls.get("acquisition_date") is not None


def test_ai_status_is_probed_not_hardcoded():
    """C-2 guard: AI/stream statuses are real probe results, never '100% ONLINE'."""
    data = client.get("/api/settings/ai-status").json()
    blob = json.dumps(data).lower()
    assert "100%" not in blob.replace(" ", "")
    for source in data.get("live_data_sources", []):
        assert source["status"] in ("online", "offline", "not_configured", "configured", "standby")
    assert data["local_engines"]["ollama_qwen2.5_3b"] in ("online", "offline")


def test_invalid_geojson_leaves_no_orphan_file():
    """Upload hygiene: a rejected GeoJSON must not persist a file on disk."""
    import backend.app.api.routes_upload as ru
    before = {p.name for p in ru.UPLOAD_DIR.iterdir()}
    files = {"file": ("broken.geojson", b"{not valid json", "application/geo+json")}
    response = client.post("/api/upload", files=files)
    assert response.status_code == 400
    after = {p.name for p in ru.UPLOAD_DIR.iterdir()}
    assert after == before, f"orphaned upload: {after - before}"


def test_corrupt_magic_valid_tiff_rejected_without_orphan():
    """A file with a valid TIFF magic byte but unreadable body must 400 and leave no orphan."""
    import backend.app.api.routes_upload as ru
    before = {p.name for p in ru.UPLOAD_DIR.iterdir()}
    files = {"file": ("corrupt.tif", b"II*\x00" + b"\x00" * 60, "image/tiff")}
    response = client.post("/api/upload", files=files)
    assert response.status_code == 400, response.text
    after = {p.name for p in ru.UPLOAD_DIR.iterdir()}
    assert after == before, f"orphaned raster: {after - before}"


@pytest.mark.slow
def test_query_ignores_traversal_uploaded_file():
    """Security guard: a traversal in uploaded_file must not read outside uploads."""
    response = client.post("/api/query", json={
        "query": "Assess terrain change", "modality": "bitemporal",
        "sector_id": "malacca-chokepoint", "uploaded_file": "../../../../etc/passwd",
    })
    assert response.status_code == 200
    assert response.json()["telemetry"]["sector_id"] == "malacca-chokepoint"


@pytest.mark.slow
def test_shared_raster_sector_discloses_simulation():
    """B-2 guard: a sector whose raster bytes are shared must disclose simulation
    in the answer itself and report imagery_distinct=False (not just baseline-different)."""
    data = client.post("/api/query", json={
        "query": "Assess terrain change", "sector_id": "joshimath-subsidence",
        "modality": "bitemporal",
    }).json()
    t = data["telemetry"]
    assert t["is_simulated"] is True
    assert t["imagery_distinct"] is False
    assert "not satellite-acquired" in t["data_provenance"]
    assert data["answer"].startswith("SIMULATED DEMO RASTER")


@pytest.mark.slow
def test_real_acquisition_sector_is_not_labelled_simulated():
    """B-3 guard: the one real-acquisition sector must not carry a simulation disclosure."""
    data = client.post("/api/query", json={
        "query": "Assess terrain change", "sector_id": "isro-sac",
        "modality": "bitemporal",
    }).json()
    t = data["telemetry"]
    assert t["is_real_image"] is True and t["is_simulated"] is False
    assert "SIMULATED DEMO RASTER" not in (data["answer"] or "")
    assert "Real Satellite Acquisition" in t["data_provenance"]

