import type { TacticalGlobePin, SectorTarget, QueryResponse, BenchmarkQuery, GeoTIFFMetadata, ModalityMode, AgentExecutionNode } from '../types';

export const TACTICAL_PINS: TacticalGlobePin[] = [
  {
    id: 'isro-sac',
    name: 'ISRO SAC Ahmedabad',
    state: 'REFERENCE SITE',
    lat: 23.0225,
    lon: 72.5074,
    zoom: 14.5,
    pitch: 45,
    badge: 'ISRO // SAC',
    category: 'base',
    pinColor: '#3B82F6',
    symbol: '🏛',
    recommendedQuery: 'Detect institutional buildings and footprint at ISRO SAC campus.',
    description: 'Space Applications Centre (SAC) - Key facility for payload design, sensor optics, and microwave remote sensing.',
    activePasses: undefined,
    defcon: 4,
    country: 'India',
    temporalDelta: undefined,
    is_real_image: true,
    is_simulated: false,
  },
  {
    id: 'sdsc-sriharikota',
    name: 'SDSC SHAR Sriharikota',
    state: 'ORBITAL LAUNCH COMPLEX',
    lat: 13.7259,
    lon: 80.2266,
    zoom: 13.8,
    pitch: 42,
    badge: 'ISRO // LAUNCHPAD',
    category: 'base',
    pinColor: '#3B82F6',
    symbol: '🚀',
    recommendedQuery: 'Assess launch complex 2 and propellant storage tanks change detection.',
    description: 'Satish Dhawan Space Centre - Primary orbital spaceport of India on the eastern seaboard.',
    activePasses: 'RISAT-2B Radar pass at 03:20 UTC',
    defcon: 4,
    country: 'India',
    temporalDelta: 'Solid Motor Test Facility Groundwork',
    is_simulated: true,
  },
  {
    id: 'galwan-sar',
    name: 'Galwan Valley Outpost',
    state: 'HIGH REVISIT MONITORING',
    lat: 34.7667,
    lon: 78.25,
    zoom: 12.5,
    pitch: 55,
    badge: 'SAR // VALLEY',
    category: 'radar',
    pinColor: '#06B6D4',
    symbol: '⚡',
    recommendedQuery: 'Pierce cloud cover with Sentinel-1 SAR to map high-altitude all-weather roadways.',
    description: 'Line of Actual Control rugged mountain sector monitored via C-Band Synthetic Aperture Radar.',
    activePasses: 'Sentinel-1B IW Ground Range Detected',
    defcon: 3,
    country: 'Himalayan Ridge',
    temporalDelta: '+1.8 km reinforced all-weather causeway',
    is_simulated: true,
  },
  {
    id: 'pokhran-range',
    name: 'Pokhran Strategic Range',
    state: 'CALIBRATION RANGE',
    lat: 27.06,
    lon: 71.75,
    zoom: 12.2,
    pitch: 35,
    badge: 'EO // CALIBRATION',
    category: 'nuclear',
    pinColor: '#EF4444',
    symbol: '🎯',
    recommendedQuery: 'Inspect subterranean excavation signatures and seismic sensor arrays.',
    description: 'Arid Thar desert testing range with controlled telemetry perimeters and hardened bunkers.',
    activePasses: 'TerraSAR-X High-Res Stripmap at 17:05 UTC',
    defcon: 3,
    country: 'India',
    temporalDelta: 'Security perimeter fence overhaul',
    is_simulated: true,
  },
  {
    id: 'malacca-chokepoint',
    name: 'Malacca Strait Corridor',
    state: 'HIGH TRAFFIC DENSITY',
    lat: 2.5,
    lon: 101.5,
    zoom: 10.5,
    pitch: 30,
    badge: 'CHOKEPOINT // MARITIME',
    category: 'maritime',
    pinColor: '#F59E0B',
    symbol: '⚓',
    recommendedQuery: 'Track maritime container vessel congestion in Singapore Strait.',
    description: 'Primary sea lane of communication connecting the Indian Ocean to the South China Sea.',
    activePasses: 'Sentinel-1 SAR Maritime Vessel Detector',
    defcon: 4,
    country: 'International Waters',
    temporalDelta: '312 merchant vessels tracked in 24hr corridor',
    is_simulated: true,
  },
  {
    id: 'suez-canal',
    name: 'Suez Canal / Great Bitter Lake',
    state: 'STRATEGIC TRANSIT',
    lat: 30.33,
    lon: 32.35,
    zoom: 11.2,
    pitch: 40,
    badge: 'CANAL // NORTH AFRICA',
    category: 'maritime',
    pinColor: '#F59E0B',
    symbol: '🚢',
    recommendedQuery: 'Analyze ship convoy spacing and bypass channel depth variance.',
    description: 'Vital 193 km artificial waterway mediating 12% of world global trade volume.',
    activePasses: 'Sentinel-2 Multispectral Overflight',
    defcon: 4,
    country: 'Egypt',
    temporalDelta: 'Dredging revetment reinforcement observed',
    is_simulated: true,
  },
  {
    id: 'brahmaputra-flood',
    name: 'Brahmaputra Floodplain Basin',
    state: 'EMERGENCY INUNDATION',
    lat: 26.15,
    lon: 91.77,
    zoom: 10.8,
    pitch: 25,
    badge: 'DISASTER // HYDRO',
    category: 'disaster',
    pinColor: '#10B981',
    symbol: '🌊',
    recommendedQuery: 'Pierce cloud cover with Sentinel-1 SAR to map flooded riverbanks.',
    description: 'Major monsoon runoff corridor. Cloud-penetrating radar tracks breach lines and embankment erosion.',
    activePasses: 'Sentinel-1 Dual-Pol (VV/VH) Water Mask',
    defcon: 4,
    country: 'India / Assam',
    temporalDelta: '14,200 hectares seasonal submergence',
    optical_t1_date: '2024-04-10',
    optical_t2_date: '2024-05-25',
    is_simulated: true,
  },
  {
    id: 'diego-garcia',
    name: 'Diego Garcia Naval Facility',
    state: 'RESTRICTED ATOLL',
    lat: -7.3195,
    lon: 72.4228,
    zoom: 12.0,
    pitch: 45,
    badge: 'USN // BIOT',
    category: 'base',
    pinColor: '#3B82F6',
    symbol: '⚓',
    recommendedQuery: 'Monitor strategic bomber tarmac parking pads and deepwater submarine tender berth.',
    description: 'British Indian Ocean Territory naval support facility with 3,600m runway and anchorage.',
    activePasses: 'Pleiades Neo 30cm Optical Pass',
    defcon: 3,
    country: 'BIOT / Indian Ocean',
    temporalDelta: 'Hangars shelter upgrade detected',
    is_simulated: true,
  },
  {
    id: 'taiwan-strait',
    name: 'Taiwan Strait Demarcation',
    state: 'ACTIVE INTERCEPT SECTOR',
    lat: 24.2,
    lon: 119.8,
    zoom: 8.8,
    pitch: 35,
    badge: 'RADAR // AIR-SEA',
    category: 'radar',
    pinColor: '#06B6D4',
    symbol: '⚡',
    recommendedQuery: 'Evaluate surface naval patrol patterns and airborne early warning orbits.',
    description: '180 km-wide strait between Taiwan island and the Asian mainland under 24/7 spaceborne surveillance.',
    activePasses: 'Constellation SAR multi-angle scan',
    defcon: 2,
    country: 'East Asia',
    temporalDelta: 'Increased naval patrol tracks across median line',
    is_simulated: true,
  },
  {
    id: 'tarapur-npp',
    name: 'Tarapur Atomic Power Station',
    state: 'CRITICAL INFRASTRUCTURE',
    lat: 19.8286,
    lon: 72.6583,
    zoom: 14.2,
    pitch: 40,
    badge: 'NUCLEAR // ENERGY',
    category: 'nuclear',
    pinColor: '#EF4444',
    symbol: '☢',
    recommendedQuery: 'Assess thermal cooling discharge plume in Arabian Sea using Sentinel-3 SLSTR.',
    description: 'Oldest commercial nuclear power station in India featuring BWR and PHWR reactor units.',
    activePasses: 'Landsat-9 Thermal Infrared Sensor (TIRS-2)',
    defcon: 4,
    country: 'India',
    temporalDelta: 'Switchyard expansion and intake cooling channel maintenance',
    is_simulated: true,
  },
  {
    id: 'bab-el-mandeb',
    name: 'Bab-el-Mandeb Strait',
    state: 'MARITIME RISK TIER 1',
    lat: 12.58,
    lon: 43.33,
    zoom: 9.8,
    pitch: 38,
    badge: 'RED SEA // TRANSIT',
    category: 'maritime',
    pinColor: '#F59E0B',
    symbol: '⚓',
    recommendedQuery: 'Track diverted commercial vessel rerouting around Cape of Good Hope.',
    description: 'Strategic chokepoint between Yemen, Djibouti, and Eritrea connecting Red Sea to Gulf of Aden.',
    activePasses: 'Synthetic Aperture Radar + AIS correlation',
    defcon: 2,
    country: 'Red Sea Gate',
    temporalDelta: '-64% commercial container throughput compared to 2023 baseline',
    is_simulated: true,
  },
  {
    id: 'sentinel-overpass-node',
    name: 'Sentinel-2A Sun-Synch Node',
    state: 'ORBITAL L2A BATCH',
    lat: 18.0,
    lon: 76.0,
    zoom: 6.0,
    pitch: 20,
    badge: 'ESA // SENTINEL-2',
    category: 'satellite',
    pinColor: '#10B981',
    symbol: '🛰',
    recommendedQuery: 'What new infrastructure was constructed between March and May 2024?',
    description: 'Active 786 km altitude sun-synchronous orbit swath delivering 13 spectral bands at 10m-60m GSD.',
    activePasses: 'Tile 43QGD captured at 05:42:19Z',
    defcon: 5,
    country: 'LEO Orbit',
    temporalDelta: 'Fresh 0% cloud tile ingested 18 mins ago',
    is_simulated: true,
  },
  {
    id: 'joshimath-subsidence',
    name: 'Joshimath Himalayan Subsidence Zone',
    state: 'CRITICAL MONITORING',
    lat: 30.5564,
    lon: 79.5667,
    zoom: 14.2,
    pitch: 50,
    badge: 'RADIOMETRIC CHANGE // SUBSIDENCE (DEMO)',
    category: 'base',
    pinColor: '#F59E0B',
    symbol: '⚠️',
    recommendedQuery: 'Detect land use and land cover change between 2023 and 2024 at Joshimath.',
    description: 'Chamoli Himalayan subsidence corridor — illustrative demo scenario evaluated with bi-temporal radiometric change detection on SAR amplitude (no InSAR/phase processing in this build).',
    activePasses: 'Sentinel-1A IW Ascending Pass (12-day repeat cycle)',
    defcon: 2,
    country: 'India (Uttarakhand)',
    temporalDelta: 'Illustrative demo displacement value (-5.4 cm) — not interferometrically measured in this build',
    is_simulated: true,
  },
  {
    id: 'siachen-glacier',
    name: 'Siachen Glacier Sector',
    state: 'STRATEGIC GLACIER',
    lat: 35.5,
    lon: 77.0,
    zoom: 12.8,
    pitch: 55,
    badge: 'SAR // GLACIOLOGY',
    category: 'radar',
    pinColor: '#06B6D4',
    symbol: '❄️',
    recommendedQuery: 'Identify high backscatter dielectric anomalies and crevasses across Siachen Glacier.',
    description: 'High-altitude Karakoram glacial icefield monitored via RISAT-1A and Sentinel-1 C-Band radar penetration.',
    activePasses: 'RISAT-1A Hybrid Polarimetric SAR at 04:15 UTC',
    defcon: 3,
    country: 'India (Ladakh)',
    temporalDelta: 'Glacial snout velocity: 14.2 cm/day seaward drift',
    is_simulated: true,
  },
];

export const SECTOR_TARGETS: SectorTarget[] = [
  {
    ...TACTICAL_PINS.find((p) => p.id === 'isro-sac'),
    region: 'Gujarat, India',
    group: 'India Strategic',
    badge: 'ISRO-SAC',
  } as SectorTarget,
  {
    id: 'sdsc-sriharikota',
    name: 'SDSC Sriharikota',
    region: 'Andhra Pradesh, India',
    group: 'India Strategic',
    lat: 13.7259,
    lon: 80.2266,
    zoom: 13.8,
    pitch: 42,
    category: 'base',
    badge: 'SHAR-LAUNCHPAD',
    is_simulated: true,
  },
  {
    id: 'galwan-sar',
    name: 'Galwan Valley Corridor',
    region: 'Ladakh, LAC',
    group: 'India Strategic',
    lat: 34.7667,
    lon: 78.25,
    zoom: 12.5,
    pitch: 55,
    category: 'radar',
    badge: 'LAC-VALLEY',
    is_simulated: true,
  },
  {
    id: 'pokhran-range',
    name: 'Pokhran Strategic Range',
    region: 'Rajasthan, India',
    group: 'India Strategic',
    lat: 27.06,
    lon: 71.75,
    zoom: 12.2,
    pitch: 35,
    category: 'nuclear',
    badge: 'POKHRAN-TEST',
    is_simulated: true,
  },
  {
    id: 'malacca-chokepoint',
    name: 'Strait of Malacca',
    region: 'Southeast Asia',
    group: 'Global Chokepoints',
    lat: 2.5,
    lon: 101.5,
    zoom: 10.5,
    pitch: 30,
    category: 'maritime',
    badge: 'MALACCA-SLOC',
    is_simulated: true,
  },
  {
    id: 'bab-el-mandeb',
    name: 'Bab-el-Mandeb Strait',
    region: 'Red Sea Entrance',
    group: 'Global Chokepoints',
    lat: 12.58,
    lon: 43.33,
    zoom: 9.8,
    pitch: 38,
    category: 'maritime',
    badge: 'BAB-MAND',
    is_simulated: true,
  },
  {
    id: 'suez-canal',
    name: 'Suez Canal / Bitter Lake',
    region: 'Egypt',
    group: 'Global Chokepoints',
    lat: 30.33,
    lon: 32.35,
    zoom: 11.2,
    pitch: 40,
    category: 'maritime',
    badge: 'SUEZ-TRANSIT',
    is_simulated: true,
  },
  {
    id: 'taiwan-strait',
    name: 'Taiwan Strait',
    region: 'East Asia',
    group: 'Global Chokepoints',
    lat: 24.2,
    lon: 119.8,
    zoom: 8.8,
    pitch: 35,
    category: 'radar',
    badge: 'TAIWAN-STRAIT',
    is_simulated: true,
  },
  {
    id: 'brahmaputra-flood',
    name: 'Brahmaputra River Basin',
    region: 'Northeast India',
    group: 'Critical Infrastructure',
    lat: 26.15,
    lon: 91.77,
    zoom: 10.8,
    pitch: 25,
    category: 'disaster',
    badge: 'FLOOD-HYDRO',
    is_simulated: true,
  },
  {
    id: 'tarapur-npp',
    name: 'Tarapur Atomic Station',
    region: 'Maharashtra, India',
    group: 'Critical Infrastructure',
    lat: 19.8286,
    lon: 72.6583,
    zoom: 14.2,
    pitch: 40,
    category: 'nuclear',
    badge: 'TARAPUR-NPP',
    is_simulated: true,
  },
  {
    id: 'diego-garcia',
    name: 'Diego Garcia Naval Base',
    region: 'Indian Ocean Atoll',
    group: 'Polar & Oceanic',
    lat: -7.3195,
    lon: 72.4228,
    zoom: 12.0,
    pitch: 45,
    category: 'base',
    badge: 'DIEGO-GARCIA',
    is_simulated: true,
  },
];

export const RECOMMENDED_PRESETS = [
  {
    id: 'p1',
    query: 'What new infrastructure was constructed between March and May 2024?',
    tag: 'BI-TEMPORAL CHANGE',
    sectorId: 'isro-sac',
    intent: 'bitemporal_change' as const,
    icon: 'Layers',
  },
  {
    id: 'p2',
    query: 'Pierce cloud cover with Sentinel-1 SAR to map flooded riverbanks.',
    tag: 'RADAR PENETRATION',
    sectorId: 'brahmaputra-flood',
    intent: 'sar_cloud_penetration' as const,
    icon: 'CloudRain',
  },
  {
    id: 'p3',
    query: 'Detect institutional buildings and footprint at ISRO SAC campus.',
    tag: 'OPTICAL VQA // SAM',
    sectorId: 'isro-sac',
    intent: 'optical_vqa' as const,
    icon: 'Building2',
  },
  {
    id: 'p4',
    query: 'Track maritime container vessel congestion in Singapore Strait.',
    tag: 'STAC DISCOVERY',
    sectorId: 'malacca-chokepoint',
    intent: 'stac_discovery' as const,
    icon: 'Ship',
  },
];

export const OFFICIAL_BENCHMARK_QUERIES: BenchmarkQuery[] = [
  {
    id: 'sih-q1-landcover',
    query: 'Describe the land-cover and major infrastructure visible in this sector.',
    category: 'land_cover',
    dataset: 'VRSBench',
    suggestedModality: 'single_image',
    targetPinId: 'isro-sac',
    paperRef: 'VRSBench: Visual Question Answering & Grounding for High-Res Earth Observation',
    description: 'Single-image VQA baseline: Multi-class land-use categorization, institutional building footprints, and road networks.',
  },
  {
    id: 'sih-q2-water-flood',
    query: 'Highlight the water bodies and flood boundaries referred to in the query.',
    category: 'flood_water',
    dataset: 'BigEarthNet.txt (arXiv:2603.29630)',
    suggestedModality: 'cross_modal',
    targetPinId: 'brahmaputra-flood',
    paperRef: 'BigEarthNet.txt: Multimodal Sentinel-1 SAR & Sentinel-2 Multispectral Dataset with Textual Annotations',
    description: 'Cross-modal extraction: Sentinel-1 C-SAR specular backscatter combined with Sentinel-2 NDWI for flood perimeter delineation.',
  },
  {
    id: 'sih-q3-bitemporal-change',
    query: 'What changed between March 2024 (T1) and May 2024 (T2), and where did the change occur?',
    category: 'bitemporal_change',
    dataset: 'CDVQA',
    suggestedModality: 'bitemporal',
    targetPinId: 'isro-sac',
    paperRef: 'CDVQA: Change Detection Visual Question Answering Benchmark',
    description: 'Bi-temporal paired analysis: Detecting new building construction, earth displacement, and change bounding polygons.',
  },
  {
    id: 'sih-q4-sar-cloud-pierce',
    query: 'Pierce cloud cover using Sentinel-1 SAR and map ground runway structures.',
    category: 'sar_cloud_penetration',
    dataset: 'ISRO SAC Cartosat/RISAT',
    suggestedModality: 'cross_modal',
    targetPinId: 'galwan-sar',
    paperRef: 'ISRO Space Applications Centre Co-Registered Cartosat-2S + RISAT-1A Evaluation Suite',
    description: 'Complementary fusion: SAR C-band microwave penetration of dense cloud cover to reconstruct high-dielectric runway tarmac.',
  },
  {
    id: 'sih-q5-builtup-trend',
    query: 'Has the built-up area increased, decreased, or remained unchanged?',
    category: 'urban_infrastructure',
    dataset: 'BigEarthNet.txt (arXiv:2603.29630)',
    suggestedModality: 'bitemporal',
    targetPinId: 'sdsc-sriharikota',
    paperRef: 'arXiv:2603.29630 - Text-Guided Multi-Label Land Cover Transition Models',
    description: 'Quantitative temporal inference: Classifying categorical urban footprint transitions between paired epochs.',
  },
];

export const SAMPLE_GEOTIFFS: GeoTIFFMetadata[] = [
  {
    id: 'gtiff-isro-sac-opt',
    fileName: 'ISRO_SAC_CARTOSAT2S_PAN_MS_202405.tif',
    sensor: 'Cartosat-2S',
    modality: 'single_image',
    gsd: '8.96m Calibrated Ground Sample Distance',
    crs: 'EPSG:4326 (WGS 84 Geographic)',
    radiometric: 'UINT8 (4 Bands: B2, B3, B4, B8)',
    cloudCoverPercent: 0.0,
    bands: ['Band 2 - Blue (490 nm)', 'Band 3 - Green (560 nm)', 'Band 4 - Red (665 nm)', 'Band 8 - NIR (842 nm)'],
    acquiredAt: '2024-05-12T05:32:10Z',
    bbox: [72.5, 23.015, 72.54, 23.035],
    previewUrl: '/api/samples/image/uploads/ISRO_SAC_CARTOSAT2S_PAN_MS_202405_thumb.jpg',
    locationName: 'ISRO SAC Ahmedabad Campus (Optical T2)',
  },
  {
    id: 'gtiff-ahmedabad-sar',
    fileName: 'SENTINEL1B_IW_GRDH_AHMEDABAD_20240330.tif',
    sensor: 'Sentinel-1 C-SAR',
    modality: 'cross_modal',
    gsd: '6.99m Calibrated Ground Range',
    crs: 'EPSG:4326 (WGS 84 Geographic)',
    radiometric: 'UINT8 Dual-Pol (VV + VH)',
    cloudCoverPercent: 0.0,
    bands: ['C-SAR VV (5.405 GHz Co-Polarization)', 'C-SAR VH (5.405 GHz Cross-Polarization)'],
    polarization: 'Dual-Pol (VV + VH)',
    acquiredAt: '2024-03-30T05:22:11Z',
    bbox: [72.5, 23.015, 72.54, 23.035],
    previewUrl: '/api/samples/image/uploads/SENTINEL1B_IW_GRDH_AHMEDABAD_20240330_thumb.jpg',
    locationName: 'Ahmedabad Urban & Industrial Corridor (SAR C-Band)',
  },
  {
    id: 'gtiff-sentinel2-t1',
    fileName: 'SENTINEL2A_MSI_L2A_T43QGE_20240327.tif',
    sensor: 'Sentinel-2 L2A',
    modality: 'bitemporal',
    gsd: '8.96m Surface Reflectance',
    crs: 'EPSG:4326 (WGS 84 Geographic)',
    radiometric: 'UINT8 (4 Bands: B2, B3, B4, B8)',
    cloudCoverPercent: 0.0,
    bands: ['Band 2 - Blue (490 nm)', 'Band 3 - Green (560 nm)', 'Band 4 - Red (665 nm)', 'Band 8 - NIR (842 nm)'],
    acquiredAt: '2024-03-27T05:22:11Z',
    bbox: [72.5, 23.015, 72.54, 23.035],
    previewUrl: '/api/samples/image/uploads/SENTINEL2A_MSI_L2A_T43QGE_20240327_thumb.jpg',
    locationName: 'ISRO SAC Ahmedabad (Epoch T1 Baseline)',
  },
  {
    id: 'gtiff-brahmaputra-sar',
    fileName: 'SENTINEL1B_IW_GRDH_BRAHMAPUTRA_20240715.tif',
    sensor: 'Sentinel-1 C-SAR',
    modality: 'cross_modal',
    gsd: '66.33m Ground Range Multi-Look',
    crs: 'EPSG:4326 (WGS 84 Geographic)',
    radiometric: 'UINT8 Dual-Pol (VV + VH)',
    cloudCoverPercent: 0.0,
    bands: ['C-SAR VV (5.405 GHz Co-Polarization)', 'C-SAR VH (5.405 GHz Cross-Polarization)'],
    polarization: 'Dual-Pol (VV + VH)',
    acquiredAt: '2024-07-15T00:18:44Z',
    bbox: [92.75, 26.55, 92.95, 26.75],
    previewUrl: '/api/samples/image/uploads/SENTINEL1B_IW_GRDH_BRAHMAPUTRA_20240715_thumb.jpg',
    locationName: 'Brahmaputra Basin Flood Inundation (SAR C-Band)',
  },
];

export const DEFAULT_LAYERS = [
  {
    id: 'intel-hotspots',
    name: 'Intel Hotspots & Bases',
    category: 'Tactical Vectors',
    color: '#3B82F6',
    assetCount: 12,
    description: 'Strategic military bases, launch complexes, and sovereign test zones.',
    visible: true,
    opacity: 100,
    bandInfo: 'GeoJSON Point Hierarchy',
  },
  {
    id: 'sentinel-optical',
    name: 'Sentinel-2 L2A (Optical)',
    category: 'Multispectral Imagery',
    color: '#10B981',
    description: '10m ground resolution visible (RGB) + Near-Infrared surface reflectance bands.',
    visible: true,
    opacity: 100,
    bandInfo: 'B2, B3, B4, B8 (10m GSD)',
  },
  {
    id: 'sentinel-sar',
    name: 'Sentinel-1 C-SAR (Radar)',
    category: 'Synthetic Aperture Radar',
    color: '#06B6D4',
    description: 'All-weather, day/night cloud penetration via 5.405 GHz C-band radar amplitude backscatter (not interferometry).',
    visible: true,
    opacity: 90,
    bandInfo: 'VV + VH Polarimetric',
  },
  {
    id: 'isro-ground-stations',
    name: 'ISRO Tracking & Telemetry',
    category: 'Ground Segment',
    color: '#F59E0B',
    assetCount: 5,
    description: 'SAC Ahmedabad, SDSC Sriharikota, NRSC Shadnagar, ISTRAC Bengaluru, MCF Hassan.',
    visible: true,
    opacity: 100,
    bandInfo: 'S/X/Ka Band Terminals',
  },
  {
    id: 'flood-inundation',
    name: 'Flood Inundation Contours',
    category: 'Dynamic Evidence',
    color: '#38BDF8',
    description: 'Dynamic SAR-derived Otsu threshold water delineation masks and risk vectors.',
    visible: true,
    opacity: 85,
    bandInfo: 'Otsu Water Index σ° < -16dB',
  },
  {
    id: 'bitemporal-structural-change',
    name: 'Bi-Temporal Structural Change',
    category: 'Change Detection',
    color: '#EF4444',
    description: 'Construction deltas, earthwork anomalies, and vegetation clearances (T1 vs T2).',
    visible: true,
    opacity: 90,
    bandInfo: 'RemoteCLIP + SAM Segmentation',
  },
];

// Sample GeoJSON feature collection generator for sectors
export function getSectorGeoJSON(sectorId: string, lat: number, lon: number): GeoJSON.FeatureCollection {
  // Generate realistic polygons surrounding the sector
  const offset = 0.005;
  const outerOffset = 0.012;

  if (sectorId === 'brahmaputra-flood') {
    // Water inundation polygons
    return {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            name: 'Active Inundation Zone A',
            class: 'Water Water-Body Inundation',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            depth_est: '1.8m - 2.4m',
            sensor: 'Sentinel-1 C-SAR',
            fillColor: '#38BDF8',
            borderColor: '#0284C7',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.03, lat - 0.01],
                [lon - 0.01, lat + 0.02],
                [lon + 0.02, lat + 0.025],
                [lon + 0.04, lat + 0.005],
                [lon + 0.02, lat - 0.02],
                [lon - 0.01, lat - 0.025],
                [lon - 0.03, lat - 0.01],
              ],
            ],
          },
        },
        {
          type: 'Feature',
          properties: {
            name: 'Embankment Breach Hazard',
            class: 'Critical Infrastructure Breach',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#EF4444',
            borderColor: '#DC2626',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon + 0.01, lat + 0.01],
                [lon + 0.025, lat + 0.015],
                [lon + 0.022, lat + 0.005],
                [lon + 0.012, lat - 0.002],
                [lon + 0.01, lat + 0.01],
              ],
            ],
          },
        },
      ],
    };
  }

  if (sectorId === 'isro-sac') {
    // Institutional building footprints and change polygon
    return {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            name: 'New Advanced Sensor Integration Cleanroom (T2 Delta)',
            class: 'Structural Expansion (T1 vs T2)',
            area_m2: 4200,
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#EF4444',
            borderColor: '#F87171',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.0025, lat + 0.001],
                [lon + 0.0015, lat + 0.0018],
                [lon + 0.002, lat - 0.0012],
                [lon - 0.002, lat - 0.002],
                [lon - 0.0025, lat + 0.001],
              ],
            ],
          },
        },
        {
          type: 'Feature',
          properties: {
            name: 'Microwave Remote Sensing Testing Facility',
            class: 'Institutional Building',
            area_m2: 8600,
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#3B82F6',
            borderColor: '#60A5FA',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon + 0.003, lat + 0.004],
                [lon + 0.007, lat + 0.004],
                [lon + 0.0068, lat + 0.001],
                [lon + 0.0028, lat + 0.001],
                [lon + 0.003, lat + 0.004],
              ],
            ],
          },
        },
        {
          type: 'Feature',
          properties: {
            name: 'Antenna Testing Range Perimeter',
            class: 'Secure Perimeter',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#10B981',
            borderColor: '#34D399',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.006, lat - 0.002],
                [lon - 0.003, lat - 0.001],
                [lon - 0.0035, lat - 0.005],
                [lon - 0.0065, lat - 0.0045],
                [lon - 0.006, lat - 0.002],
              ],
            ],
          },
        },
      ],
    };
  }

  if (sectorId === 'sdsc-sriharikota') {
    return {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            name: 'Second Launch Pad (SLP) Umbilical Complex',
            class: 'Spaceport Launch Infrastructure',
            area_m2: 12400,
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#3B82F6',
            borderColor: '#60A5FA',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.003, lat + 0.002],
                [lon + 0.003, lat + 0.002],
                [lon + 0.003, lat - 0.003],
                [lon - 0.003, lat - 0.003],
                [lon - 0.003, lat + 0.002],
              ],
            ],
          },
        },
        {
          type: 'Feature',
          properties: {
            name: 'First Launch Pad (FLP) Mount & Flame Deflector',
            class: 'Spaceport Launch Infrastructure',
            area_m2: 9800,
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#10B981',
            borderColor: '#34D399',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.006, lat + 0.015],
                [lon - 0.001, lat + 0.015],
                [lon - 0.001, lat + 0.010],
                [lon - 0.006, lat + 0.010],
                [lon - 0.006, lat + 0.015],
              ],
            ],
          },
        },
        {
          type: 'Feature',
          properties: {
            name: 'Solid Propellant Booster Plant (SPROB Delta)',
            class: 'Propellant Processing Complex',
            area_m2: 16500,
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#F59E0B',
            borderColor: '#FBBF24',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.012, lat - 0.008],
                [lon - 0.005, lat - 0.008],
                [lon - 0.005, lat - 0.015],
                [lon - 0.012, lat - 0.015],
                [lon - 0.012, lat - 0.008],
              ],
            ],
          },
        },
      ],
    };
  }

  if (sectorId === 'galwan-sar') {
    return {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            name: 'DSDBO All-Weather Causeway Embankment',
            class: 'Transport Infrastructure (SAR Delineated)',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#06B6D4',
            borderColor: '#22D3EE',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.018, lat - 0.004],
                [lon - 0.005, lat + 0.002],
                [lon + 0.012, lat + 0.008],
                [lon + 0.015, lat + 0.006],
                [lon - 0.002, lat - 0.001],
                [lon - 0.016, lat - 0.007],
                [lon - 0.018, lat - 0.004],
              ],
            ],
          },
        },
        {
          type: 'Feature',
          properties: {
            name: 'River Confluence Hardened Bunker Redoubt',
            class: 'High-Dielectric Radar Scatterer',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#EF4444',
            borderColor: '#F87171',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon + 0.001, lat - 0.001],
                [lon + 0.005, lat - 0.001],
                [lon + 0.005, lat - 0.004],
                [lon + 0.001, lat - 0.004],
                [lon + 0.001, lat - 0.001],
              ],
            ],
          },
        },
      ],
    };
  }

  if (sectorId === 'pokhran-range') {
    return {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            name: 'Subterranean Shaft Collar & Diagnostic Enclosure',
            class: 'Controlled Strategic Calibration AOI',
            area_m2: 6400,
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#EF4444',
            borderColor: '#F87171',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.004, lat + 0.003],
                [lon + 0.004, lat + 0.003],
                [lon + 0.004, lat - 0.003],
                [lon - 0.004, lat - 0.003],
                [lon - 0.004, lat + 0.003],
              ],
            ],
          },
        },
        {
          type: 'Feature',
          properties: {
            name: 'Seismic Telemetry Perimeter Fence',
            class: 'Secure Perimeter Buffer',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#F59E0B',
            borderColor: '#FBBF24',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.012, lat + 0.010],
                [lon + 0.012, lat + 0.010],
                [lon + 0.012, lat - 0.010],
                [lon - 0.012, lat - 0.010],
                [lon - 0.012, lat + 0.010],
              ],
            ],
          },
        },
      ],
    };
  }

  if (sectorId === 'malacca-chokepoint') {
    return {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            name: 'Traffic Separation Scheme (TSS) Eastbound Shipping Lane',
            class: 'Maritime Transit Corridor',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#38BDF8',
            borderColor: '#0284C7',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.025, lat + 0.010],
                [lon + 0.025, lat + 0.018],
                [lon + 0.028, lat + 0.011],
                [lon - 0.022, lat + 0.003],
                [lon - 0.025, lat + 0.010],
              ],
            ],
          },
        },
      ],
    };
  }

  if (sectorId === 'tarapur-npp') {
    return {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            name: 'Reactor Unit 1-4 Containment Dome Facility',
            class: 'Critical Infrastructure Nuclear',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#EF4444',
            borderColor: '#F87171',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.003, lat + 0.003],
                [lon + 0.003, lat + 0.003],
                [lon + 0.003, lat - 0.003],
                [lon - 0.003, lat - 0.003],
                [lon - 0.003, lat + 0.003],
              ],
            ],
          },
        },
        {
          type: 'Feature',
          properties: {
            name: 'Arabian Sea Coolant Discharge Plume Channel',
            class: 'Hydrological Thermal Effluent',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#06B6D4',
            borderColor: '#22D3EE',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.008, lat + 0.001],
                [lon - 0.003, lat + 0.002],
                [lon - 0.003, lat - 0.002],
                [lon - 0.008, lat - 0.004],
                [lon - 0.008, lat + 0.001],
              ],
            ],
          },
        },
      ],
    };
  }

  if (sectorId === 'joshimath-subsidence') {
    return {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          properties: {
            name: 'Ravigram-Sunil Ward Subsidence Fracture Escarpment',
            class: 'Geological Slope Displacement Zone',
            isReference: true,
            provenance: 'Sector Baseline Vector',
            fillColor: '#F59E0B',
            borderColor: '#D97706',
          },
          geometry: {
            type: 'Polygon',
            coordinates: [
              [
                [lon - 0.006, lat + 0.004],
                [lon + 0.002, lat + 0.006],
                [lon + 0.007, lat + 0.001],
                [lon + 0.004, lat - 0.004],
                [lon - 0.003, lat - 0.003],
                [lon - 0.006, lat + 0.004],
              ],
            ],
          },
        },
      ],
    };
  }
  return {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        properties: {
          name: `${sectorId.toUpperCase()} Core Operations Perimeter`,
          class: 'Strategic Vector',
          isReference: true,
          provenance: 'Sector Baseline Vector',
          fillColor: '#3B82F6',
          borderColor: '#60A5FA',
        },
        geometry: {
          type: 'Polygon',
          coordinates: [
            [
              [lon - offset, lat - offset],
              [lon + offset, lat - offset],
              [lon + offset, lat + offset],
              [lon - offset, lat + offset],
              [lon - offset, lat - offset],
            ],
          ],
        },
      },
      {
        type: 'Feature',
        properties: {
          name: `${sectorId.toUpperCase()} High-Precision STAC Bounding Box`,
          class: 'Sensor Coverage AOI',
          isReference: true,
          provenance: 'Sector Baseline Vector',
          fillColor: '#06B6D4',
          borderColor: '#22D3EE',
        },
        geometry: {
          type: 'Polygon',
          coordinates: [
            [
              [lon - outerOffset, lat - outerOffset],
              [lon + outerOffset, lat - outerOffset],
              [lon + outerOffset, lat + outerOffset],
              [lon - outerOffset, lat + outerOffset],
              [lon - outerOffset, lat - outerOffset],
            ],
          ],
        },
      },
    ],
  };
}
