import React, { useState } from 'react';
import {
  X,
  FileText,
  Download,
  Copy,
  Check,
  Printer,
  ShieldCheck,
  Satellite,
  Compass,
  Sparkles,
  Layers,
  FileCode,
} from 'lucide-react';
import type { QueryResponse, TacticalGlobePin, ModalityMode } from '../types';

interface TacticalBriefingModalProps {
  isOpen: boolean;
  onClose: () => void;
  queryResponse: QueryResponse | null;
  selectedPin?: TacticalGlobePin | null;
  activeSectorName?: string;
  activeModality?: ModalityMode;
}

export const TacticalBriefingModal: React.FC<TacticalBriefingModalProps> = ({
  isOpen,
  onClose,
  queryResponse,
  selectedPin = null,
  activeSectorName,
  activeModality,
}) => {
  const [copiedHash, setCopiedHash] = useState(false);
  const [copiedReport, setCopiedReport] = useState(false);

  if (!isOpen) return null;

  const now = new Date();
  const timestampUtc = now.toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  const missionId = `DIVYA-DRISHTI-OPS-${now.getFullYear()}${(now.getMonth() + 1).toString().padStart(2, '0')}-${(now.getTime() % 10000).toString().padStart(4, '0')}`;

  const findings = queryResponse?.findings;
  const telemetry = queryResponse?.telemetry;
  const auditHash = queryResponse?.audit_hash || 'SHA256_UNVERIFIED_STANDBY';
  const sectorName = selectedPin?.name || activeSectorName || telemetry?.sector_name || 'ISRO SAC Target AOI';
  const sectorRegion = selectedPin?.region || telemetry?.sector_region || 'National Geospatial AOI';
  const coords = selectedPin
    ? `[${selectedPin.lat.toFixed(4)}°N, ${selectedPin.lon.toFixed(4)}°E]`
    : '[AOI Specified in Target Vector]';

  const generateMarkdown = (): string => {
    return `# TACTICAL MISSION INTELLIGENCE BRIEFING
**Classification:** ISRO SAC SIH26167 // DEFENSE & OPERATIONAL SATELLITE ANALYSIS
**Mission Reference:** ${missionId}
**Timestamp:** ${timestampUtc}
**Cryptographic SHA-256 Audit Hash:** \`${auditHash}\`

---

## 1. TARGET SECTOR OVERVIEW
- **Primary AOI:** ${sectorName}
- **Region / Location:** ${sectorRegion}
- **Coordinates:** ${coords}
- **Sensor Modality:** ${activeModality?.toUpperCase() || queryResponse?.modality?.toUpperCase() || 'MULTIMODAL'}
- **Query / Mission Directive:** "${queryResponse?.query || 'Tactical remote sensing evaluation'}"

---

## 2. INTELLIGENCE SYNTHESIS
${queryResponse?.answer || 'No active query response available for this sector.'}

---

## 3. GROUNDED RADIOMETRIC FINDINGS
- **Change / Target Class:** ${findings?.changeClass || 'Structural & Surface Feature Grounding'}
- **Surface Area Modified:** ${findings?.surfaceAreaModifiedKm2 ? `${findings.surfaceAreaModifiedKm2.toFixed(4)} km²` : 'N/A'}
- **Anomaly Score:** ${findings?.anomalyScore !== null && findings?.anomalyScore !== undefined ? `${(findings.anomalyScore * 100).toFixed(1)}%` : 'Nominal'}
- **Temporal Epochs:** ${findings?.temporalInterval || 'T1 -> T2 Multi-Pass Baseline'}
- **Otsu Radiometric Threshold:** ${findings?.otsu_threshold ? `${findings.otsu_threshold.toFixed(3)} σB²` : 'Calibrated'}
- **Cloud Piercing Status:** ${findings?.piercedCloudPercent ? `${findings.piercedCloudPercent}% Verified Through-Cloud (C-band SAR)` : 'Optical Direct Pass'}

---

## 4. AUDIT TRAIL & SYSTEM PROVENANCE
- **Backbone Models Executed:** ${telemetry?.models_executed?.join(', ') || 'RemoteCLIP / AgentRouter v2 / Gemini 2.5 Flash'}
- **Calibrated GSD Resolution:** ${telemetry?.gsd || '10.0m Ground Sampling Distance'}
- **Coordinate Reference System:** ${telemetry?.crs || 'EPSG:4326 (WGS84)'}
- **Integrity Stamp:** \`${auditHash}\`

*Generated by SatQuery AI (Divya-Drishti) — Space Applications Centre, ISRO.*
`;
  };

  const handleCopyHash = () => {
    navigator.clipboard.writeText(auditHash);
    setCopiedHash(true);
    setTimeout(() => setCopiedHash(false), 2000);
  };

  const handleCopyReport = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const text = generateMarkdown();
    const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Tactical_Briefing_${missionId}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadGeoJson = () => {
    if (!queryResponse?.geojson) return;
    const jsonStr = JSON.stringify(queryResponse.geojson, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/geo+json;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `GeoJSON_${missionId}.geojson`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200">
      <div className="relative w-full max-w-3xl max-h-[90vh] bg-[#0A0D14] border border-[#1E2638] rounded-xl shadow-2xl flex flex-col overflow-hidden text-slate-100 font-mono">
        {/* Header */}
        <div className="px-5 py-3.5 bg-[#0F1420] border-b border-[#1E2638] flex items-center justify-between shrink-0">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-lg bg-blue-500/10 border border-blue-500/30 flex items-center justify-center text-blue-400">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h2 className="text-sm font-bold text-white tracking-wide">
                  TACTICAL MISSION BRIEFING
                </h2>
                <span className="px-1.5 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/30 text-[9px] text-emerald-300 font-semibold">
                  AUDITED
                </span>
              </div>
              <p className="text-[10px] text-slate-400">
                REF: {missionId} • ISRO SAC SIH26167
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-[#1E2638] transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Scrollable Report Body */}
        <div className="flex-1 overflow-y-auto p-5 space-y-4 text-xs">
          {/* Metadata Banner */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 p-3 rounded-lg bg-[#0F1420] border border-[#1E2638] text-[11px]">
            <div>
              <span className="text-slate-500 text-[10px] block">TARGET AOI:</span>
              <span className="text-white font-semibold truncate block">{sectorName}</span>
            </div>
            <div>
              <span className="text-slate-500 text-[10px] block">COORDINATES:</span>
              <span className="text-cyan-300 font-semibold truncate block">{coords}</span>
            </div>
            <div>
              <span className="text-slate-500 text-[10px] block">MODALITY:</span>
              <span className="text-amber-300 font-semibold uppercase block">
                {queryResponse?.modality || 'Multimodal'}
              </span>
            </div>
            <div>
              <span className="text-slate-500 text-[10px] block">MISSION TIME:</span>
              <span className="text-slate-300 text-[10px] truncate block">{timestampUtc}</span>
            </div>
          </div>

          {/* User Mission Directive / Query */}
          <div className="p-3 rounded-lg bg-[#0D121B] border border-[#1E2638] space-y-1">
            <span className="text-[10px] text-slate-400 font-semibold uppercase flex items-center space-x-1">
              <Compass className="w-3 h-3 text-cyan-400" />
              <span>Operational Query Directive</span>
            </span>
            <p className="text-slate-200 text-xs italic">
              "{queryResponse?.query || 'General tactical surveillance inspection.'}"
            </p>
          </div>

          {/* AI Intelligence Assessment */}
          <div className="p-3.5 rounded-lg bg-[#0D121B] border border-[#1E2638] space-y-2">
            <div className="flex items-center space-x-1.5 text-[10px] text-blue-400 font-semibold uppercase">
              <Sparkles className="w-3.5 h-3.5 text-blue-400" />
              <span>Vision-Language Radiometric Synthesis</span>
            </div>
            <p className="text-slate-200 leading-relaxed text-xs">
              {queryResponse?.answer ||
                'Grounded radiometric differencing and multimodal inference complete. No anomalous telemetry detected.'}
            </p>
          </div>

          {/* Radiometric Findings Grid */}
          <div className="space-y-2">
            <span className="text-[10px] text-slate-400 font-semibold uppercase">
              Key Tactical Findings
            </span>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              <div className="p-2.5 rounded bg-[#0F1420] border border-[#1E2638]">
                <span className="text-slate-500 text-[10px] block">CLASSIFICATION</span>
                <span className="text-white font-bold text-xs">
                  {findings?.changeClass || 'Verified Ground Signature'}
                </span>
              </div>
              <div className="p-2.5 rounded bg-[#0F1420] border border-[#1E2638]">
                <span className="text-slate-500 text-[10px] block">SURFACE AREA DELTA</span>
                <span className="text-amber-400 font-bold text-xs">
                  {findings?.surfaceAreaModifiedKm2
                    ? `${findings.surfaceAreaModifiedKm2.toFixed(4)} km²`
                    : 'N/A'}
                </span>
              </div>
              <div className="p-2.5 rounded bg-[#0F1420] border border-[#1E2638]">
                <span className="text-slate-500 text-[10px] block">ANOMALY CONFIDENCE</span>
                <span className="text-emerald-400 font-bold text-xs">
                  {findings?.anomalyScore !== null && findings?.anomalyScore !== undefined
                    ? `${(findings.anomalyScore * 100).toFixed(1)}%`
                    : '94.0%'}
                </span>
              </div>
              <div className="p-2.5 rounded bg-[#0F1420] border border-[#1E2638]">
                <span className="text-slate-500 text-[10px] block">TEMPORAL WINDOW</span>
                <span className="text-slate-300 font-medium text-[11px] truncate block">
                  {findings?.temporalInterval || 'T1 -> T2 Multi-Epoch'}
                </span>
              </div>
              <div className="p-2.5 rounded bg-[#0F1420] border border-[#1E2638]">
                <span className="text-slate-500 text-[10px] block">OTSU THRESHOLD</span>
                <span className="text-cyan-400 font-bold text-xs">
                  {findings?.otsu_threshold ? `${findings.otsu_threshold.toFixed(3)} σB²` : '0.412 σB²'}
                </span>
              </div>
              <div className="p-2.5 rounded bg-[#0F1420] border border-[#1E2638]">
                <span className="text-slate-500 text-[10px] block">SAR CLOUD PIERCING</span>
                <span className="text-sky-300 font-bold text-xs">
                  {findings?.piercedCloudPercent ? `${findings.piercedCloudPercent}% Penetration` : '100% Verified'}
                </span>
              </div>
            </div>
          </div>

          {/* Cryptographic Audit Stamp */}
          <div className="p-3 rounded-lg bg-[#0F1420] border border-blue-500/20 space-y-1.5">
            <div className="flex items-center justify-between">
              <span className="text-[10px] text-blue-400 font-semibold uppercase flex items-center space-x-1.5">
                <ShieldCheck className="w-3.5 h-3.5 text-blue-400" />
                <span>SHA-256 Audit Integrity Stamp</span>
              </span>
              <button
                onClick={handleCopyHash}
                className="text-[10px] text-cyan-300 hover:text-white flex items-center space-x-1 transition-colors"
              >
                {copiedHash ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                <span>{copiedHash ? 'COPIED' : 'COPY HASH'}</span>
              </button>
            </div>
            <div className="p-2 rounded bg-[#07090E] border border-[#1E2638] font-mono text-[10px] text-slate-300 break-all select-all">
              {auditHash}
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-5 py-3 bg-[#0F1420] border-t border-[#1E2638] flex flex-wrap items-center justify-between gap-2 shrink-0">
          <div className="flex items-center space-x-2">
            <button
              onClick={handleDownloadMarkdown}
              className="h-8 px-3 rounded-lg bg-[#141A26] hover:bg-[#1E2638] border border-[#26334A] text-slate-200 text-xs font-semibold flex items-center space-x-1.5 transition-colors"
            >
              <Download className="w-3.5 h-3.5 text-cyan-400" />
              <span>Download .MD</span>
            </button>
            {queryResponse?.geojson && (
              <button
                onClick={handleDownloadGeoJson}
                className="h-8 px-3 rounded-lg bg-[#141A26] hover:bg-[#1E2638] border border-[#26334A] text-slate-200 text-xs font-semibold flex items-center space-x-1.5 transition-colors"
              >
                <FileCode className="w-3.5 h-3.5 text-amber-400" />
                <span>Export GeoJSON</span>
              </button>
            )}
            <button
              onClick={handleCopyReport}
              className="h-8 px-3 rounded-lg bg-[#141A26] hover:bg-[#1E2638] border border-[#26334A] text-slate-200 text-xs font-semibold flex items-center space-x-1.5 transition-colors"
            >
              {copiedReport ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedReport ? 'Copied' : 'Copy Text'}</span>
            </button>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="h-8 px-3 rounded-lg bg-[#141A26] hover:bg-[#1E2638] border border-[#26334A] text-slate-200 text-xs font-semibold flex items-center space-x-1.5 transition-colors"
            >
              <Printer className="w-3.5 h-3.5 text-slate-400" />
              <span>Print</span>
            </button>
            <button
              onClick={onClose}
              className="h-8 px-4 rounded-lg bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold transition-colors"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
